# Generated by Django 5.1 on 2024-10-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budjet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
    ]
